### ISSUE TITLE
ContextConfigurator.java Smelly Code: OO Abuser 1

### ISSUE THREAD

**Issue by edraprasetio** [jakecomp/fitnesse#12]
**Problem**
There are a few methods that are using switch statements in ContextConfigurator.java, one of those methods is called withRootDirectoryName. Using a switch statement is a part of imperative programming, we prefer to have polymorphism in OO.

**Solution**
Replace the type codes with subclasses and conditionals with polymorphism

**Additional context**
Attached is an image of the method for context.

![image](https://user-images.githubusercontent.com/67980359/157369897-34d90587-652e-4abf-a274-820c3b309dc2.png)

**Comment by jakecomp** [comment]
You can find the test file for this class in `test/fitnesse/ContextConfiguratorTest.java`

**Comment by edraprasetio** [comment]
Instead of an OO abuse, I can conclude that the smelly codes relate to a bloater. Which I resolved using an extract method refactoring tool.

**Comment by edraprasetio** [comment]
Issue resolved

**Comment by edraprasetio** [comment]
<img width="908" alt="Screen Shot 2022-03-15 at 14 49 40" src="https://user-images.githubusercontent.com/67980359/158478507-aff40afb-e3db-4d66-b927-bff519ae5d1d.png">
<img width="907" alt="Screen Shot 2022-03-15 at 14 49 52" src="https://user-images.githubusercontent.com/67980359/158478514-aa8e205a-15a4-4a5a-9702-64be67cc252a.png">

**Comment by edraprasetio** [comment]
![image](https://user-images.githubusercontent.com/67980359/158511320-74e31088-fbc3-477e-8699-d1d347901556.png)

**Comment by edraprasetio** [comment]
![image](https://user-images.githubusercontent.com/67980359/158511932-f1c412bd-0329-4a02-9361-3861df58d182.png)
