### ISSUE TITLE
Smelly Code: Repeated if checks

### ISSUE THREAD

**Issue by jberryman566** [jakecomp/fitnesse#16]
**Describe the bug**
Smelly code found. Repeated if statements for processing if a value is true (or various forms.)

**Screenshots**
![image](https://user-images.githubusercontent.com/29262049/158478378-28e2bd04-bdd8-4620-9b95-66aa97c24621.png)

**Solution:**
Suggest extracting the true checks into a separate method. Assign an array of possible strings and check if string is in array.

**Comment by jberryman566** [comment]
Code is found in TypeAdapter.java

**Comment by edraprasetio** [comment]
Snapshots of the code working after the refactor. Includes passing test cases

<img width="1314" alt="Screen Shot 2022-03-15 at 15 21 58" src="https://user-images.githubusercontent.com/67980359/158482364-3d6198ea-1269-4f6a-a1f5-9898bd8a7ddf.png">
<img width="953" alt="Screen Shot 2022-03-15 at 15 22 38" src="https://user-images.githubusercontent.com/67980359/158482370-245b805f-b7f9-45df-880c-89bca0850363.png">
<img width="945" alt="Screen Shot 2022-03-15 at 15 23 26" src="https://user-images.githubusercontent.com/67980359/158482371-9e888453-9373-400b-bdff-3ae5100b85a8.png">

**Comment by jberryman566** [comment]
Solution has been implemented. See snippet below:

![image](https://user-images.githubusercontent.com/29262049/158482286-0d43a484-c223-41a1-9e6a-9c2b575d567a.png)
