### ISSUE TITLE
Create workflow for develop branch

### ISSUE THREAD

**Issue by jakecomp** [jakecomp/fitnesse#3]
## Task ## 
Create a workflow which runs the build, unit test, and acceptance test for our project 

### Events which should trigger the workflow ### 
- Push 
- Pull Request 

### Commands to be run ### 
- `./gradlew` which builds the project 
- `./gradlew test` which runs all unit tests 
- `./gradlew acceptanceTest` which runs all acceptance tests

**Comment by jakecomp** [comment]
I think we need to give some better names to the workflows. I'm going to rename the master workflow to master_ci.yml. Would you be able to rename the develop workflow develop_ci.yml?

**Comment by edraprasetio** [comment]
Workflow has been merged with the master branch
