### ISSUE TITLE
Implement build matrix for workflows

### ISSUE THREAD

**Issue by jakecomp** [jakecomp/fitnesse#4]
## Task ## 
Implement build matrix for all workflows   

Handy link on build matrix: [(https://docs.github.com/en/actions/using-jobs/using-a-build-matrix-for-your-jobs)](url)

### Criteria for Matrix builds ### 
Some good candidates to use for our matrix build can be: 
- Different OS versions (Ubuntu, Mac, Windows)  
- Different Java versions (Note: we have experienced issues with newer versions of Java so may not be the best choice) 
- Different Gradle versions

**Comment by jberryman566** [comment]
Matrix has been set up for multiple versions of ubuntu
